name: CI

on:
  push:
    branches: [ v2 ]
  pull_request:
    branches: [ v2 ]

jobs:
  run-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0  # OR "2" -> To retrieve the preceding commit.

      - uses: astral-sh/setup-uv@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: uv sync --group dev

      - name: Run tests
        run: uv run pytest -v

  validate-resources:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0  # OR "2" -> To retrieve the preceding commit.

      - uses: astral-sh/setup-uv@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: uv sync

      - name: Get changed resource files
        id: changed-files
        uses: tj-actions/changed-files@v46
        with:
          files: src/public_schema/resources/**/*.dataresource.yaml

      - name: Validate data against changed schemas
        if: steps.changed-files.outputs.any_changed == 'true'
        run: python -m public_schema ${{ steps.changed-files.outputs.all_changed_files }}
