name: Test Resources
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
jobs:
  Validate:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        product:
          - bgc_plankton
          - bgc_combined
          - bgc_lfish
          - derived_indices
          - cpr
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r code/requirements.txt
      - name: Validate data against schemas
        run: code/validate.py $(grep ${{ matrix.product }} product_index.csv | cut -d, -f2)
