name: Test Resources
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
jobs:
  Validate:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        files: ['bgc_data/bgc_*.yaml', 'cpr_data/cpr_*.yaml']
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.6
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r code/requirements.txt
      - name: Validate data against schemas
        run: code/validate.py ${{ matrix.files }}
