name: Test Schemas
on: push
jobs:
  Test-IMOS-BGC-schemas:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.6
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r code/requirements.txt
      - name: Validate schema definitions
        run: |
          for schema in imos_bgc_db/*.schema.yaml; do
            echo Validating ${schema}
            frictionless validate $schema
          done
