name: Test Resources
on:
  push:
    branches: [ master, v2 ]
  pull_request:
    branches: [ master, v2 ]
jobs:
  Validate-BGC-CPR:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0  # OR "2" -> To retrieve the preceding commit.

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: pip install 'frictionless>=5'

      - name: Get changed resource files
        id: changed-files
        uses: tj-actions/changed-files@v46
        with:
          files: |
            bgc_data/*.dataresource.yaml
            cpr_data/*.dataresource.yaml

      - name: Validate data against changed schemas
        if: steps.changed-files.outputs.any_changed == 'true'
        run: src/validate.py ${{ steps.changed-files.outputs.all_changed_files }}
